name: MV
title: MV | Blog
description: Marco Varela's Blog
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
show_get_theme_btn: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  # - title: Feed
  #   url: /feed.xml
email: marcovarela12@gmail.com
# See: https://disqus.com/
disqus_username: mv-blog
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mbjvddng
